#!/bin/bash
#
# wallup
#   Update wallpaper images on a timed basis.

# This directory contains images to use as desktop wallpaper.
DEFAULT_WPHOME="$HOME/Pictures/Wallpaper"

# Any files with the following file extensions will be used.
WPEXTS=(jpg png gif jpeg JPG)

# This is the interval between wallpaper image updates, in seconds.
WPTIME=$((10 * 60))

# The first wallpaper image is displayed after this many seconds.
# NOTE: Subsequent images are updated every WPTIME seconds.
WPWAIT=0

# Verify the parameter is an integer, else use the default (above).
if [ "$1" -eq "$1" ] 2> /dev/null; then
    WPWAIT=$1
fi

# This is the name of the subdirectory to place the images
# that have been previously selected at random for wallpaper.
WPSAVE=.wpsave

# This variable enables two images to be used side-by-side for
# a dual monitor configuration.
WPDUAL=true

# These variables are the pixel dimensions of the dual monitors.
WPMONX=1920
WPMONY=1080

# This integer is incremented each time "convert" joins two images.
WPCVTS=1
WPCVTF=cvt-

# Prior to running this script, set the WPHOME environment
# variable to set a non-default wallpaper folder.
if [[ -z "$WPHOME" ]]; then
    if [[ -d "$DEFAULT_WPHOME" ]];  then WPHOME=$DEFAULT_WPHOME
    elif [[ -d "$HOME/Pictures" ]]; then WPHOME=$HOME/Pictures
    else                                 WPHOME=$HOME
    fi
fi

WPDEST="$WPHOME"/"$WPSAVE"
if [[ ! -d "$WPDEST" ]]; then
    mkdir "$WPDEST"
    if [[ $? != 0 ]]; then
        echo "Unable to create $WPDEST. Exiting..."
        exit
    fi
fi

function getdate {
    printf -v WPDATE '%-5d %s %s' $$ $(date +"%D %I:%M%p")
}
getdate

WPHIST="$WPDEST"/wallup.log
WPLOCK="$WPDEST"/.mult-lock
WPLPID="$WPLOCK"/lock-$$

echo "$WPDATE  Starting wallpaper updater for user $USER." >> "$WPHIST"

WPXRANDR="$WPHOME"/.screen
xrandr --query > "$WPXRANDR"
WPMONCNT=$(grep ' connected' "$WPXRANDR" | wc -l)
if [[ $WPMONCNT -eq 1 ]]; then
    WPDUAL=false
    echo "There is one monitor connected to this system."
elif [[ $WPMONCNT -eq 2 ]]; then
    WPDUAL=true
    echo "There are two monitors connected to this system."
else
    echo "There are $WPMONCNT monitors, cannot run wallpaper updater."
    exit
fi

WPSCREEN=($(awk '/Screen/ && sub(/.*current /, "") \
                          && sub(/x /,"") && sub(/,.*/,"")' "$WPXRANDR"))
echo "Screen is ${WPSCREEN[0]} pixels wide and ${WPSCREEN[1]} pixels tall."

exit

if $WPDUAL; then
    # Check if we can merge two images for the background.
    hash convert >& /dev/null
    if [[ $? -ne 0 ]]; then
        WPDUAL=false
        echo "$WPDATE  Install \"imagemagick\" for dual displays." >> "$WPHIST"
        echo "$WPDATE  ->  (sudo apt install imagemagick)" >> "$WPHIST"
    else
        # Scan for any existing converted files.
        WPFILE="$WPDEST"/"${WPCVTF}${WPCVTS}.png"
        while [[ -f "$WPFILE" ]]; do
            ((WPCVTS+=1))
            WPFILE="$WPDEST"/"${WPCVTF}${WPCVTS}.png"
        done 
    fi
fi

# If an old lock file exists, clear it out now.
if [[ -d "$WPLOCK" ]]; then
    for oldfile in "$WPLOCK"/*; do
        if [[ -f "$oldfile" ]]; then
            echo "$WPDATE  Removing old lock \"$oldfile\"." >> "$WPHIST"
            rm "$oldfile"
        fi
    done
else
    mkdir "$WPLOCK"
fi

# Create a new lock file for this process ID
touch "$WPLPID"

# Randomly select the next wallpaper image to be displayed.
function getrandom {
    cd "$WPHOME"
    WPNEXT=$(ls ${WPEXTS[@]/#/"*."} 2> /dev/null | shuf -n 1)
}

# Restore all of the previously displayed images back to the home folder.
function restore {
    cd "$WPDEST"

    # Clear out the temporary conglomerate image files.
    WPCVTS=1
    rm "$WPCVTF"*.png

    # Count the total number of images being moved for diagnostic purposes.
    WPFCNT=$(ls -1 ${WPEXTS[@]/#/"*."} 2> /dev/null | wc -l)
    echo "$WPDATE  Moving $WPFCNT image files from $WPSAVE back up to $WPHOME." >> "$WPHIST"
    mv ${WPEXTS[@]/#/"*."} "$WPHOME" 2> /dev/null
}

# Get the next wallpaper image to be dislayed.
function getnext {
    getrandom
    if [[ "$WPNEXT" == "" ]]; then
        restore
        getrandom

        # Quit now if there are no images in the wallpaper folder.
        if [[ "$WPNEXT" == "" ]]; then
            echo "$WPDATE  No Wallpaper images found in $WPHOME. Exiting..." >> "$WPHIST"
            rm -f "$WPLPID"
            exit
        fi
    fi
}

# Responsiveness to logout or multiple instances is determined
# by the WPRESP variable, the time to respond in seconds.
WPRESP=10

while true; do

    while [[ $WPWAIT -gt 0 ]]; do
        if [[ ! -f "$WPLPID" ]]; then
            getdate
            echo "$WPDATE  Missing \"$WPLPID\". Exiting..." >> "$WPHIST"
            exit
        fi

        sleep $WPRESP
        WPWAIT=$((WPWAIT - WPRESP))

        if [[ $(ps -C gnome-shell -o euser= | grep $USER) == "" ]]; then
            getdate
            echo "$WPDATE  User $USER not logged in. Exiting..." >> "$WPHIST"
            rm -f "$WPLPID"
            exit
        fi
    done
    WPWAIT=$WPTIME

    # If the destination directory disappeared while we were waiting, exit now.
    if [[ ! -d "$WPDEST" ]]; then
        echo "No directory $WPDEST. Exiting..."
        exit
    fi

    getdate

    getnext

    if $WPDUAL; then
        WPNEXT1=$WPNEXT
        mv "$WPHOME"/"$WPNEXT1" "$WPHOME"/"$WPNEXT1".HOLD
        getnext
        WPNEXT2=$WPNEXT
        mv "$WPHOME"/"$WPNEXT1".HOLD "$WPDEST"/"$WPNEXT1"
        mv "$WPHOME"/"$WPNEXT2" "$WPDEST"

        # Create the merged background image.
        WPFILE="$WPDEST"/"${WPCVTF}${WPCVTS}.png"
        ((WPCVTS+=1))

        cd "$WPDEST"
        CVTOVRH=cvt-ovr.png
        CVTFLAGS="-resize ${WPMONX}x${WPMONY}^ -gravity center -crop ${WPMONX}x${WPMONY}+0+0"
        cp ../.overhang-blk $CVTOVRH
        convert "$WPNEXT1" $CVTFLAGS wall1.png
        convert "$WPNEXT2" $CVTFLAGS wall2.png
        convert "$CVTOVRH" wall1.png -append junk1.png
        convert wall2.png "$CVTOVRH" -append junk2.png
        convert junk1.png junk2.png +append "$WPFILE"
        rm $CVTOVRH wall1.png wall2.png junk1.png junk2.png

        echo "$WPDATE  New wallpaper file://$WPFILE (from $WPNEXT1 + $WPNEXT2)" >> "$WPHIST"
    else
        mv "$WPHOME"/"$WPNEXT" "$WPDEST"
        WPFILE="$WPDEST"/"$WPNEXT"
        echo "$WPDATE  New wallpaper file://$WPFILE" >> "$WPHIST"
    fi

    gsettings set org.gnome.desktop.background picture-uri file://"$WPFILE"

done
